services:
  app:
    build: .
    image: wpg-bus-display:latest
    container_name: wpg-bus
    env_file:
      - .env
    restart: unless-stopped
    expose:
      - '3009'

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: wpg-bus-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - app
