services:
  app:
    build: .
    image: wpg-bus-display:latest
    container_name: wpg-bus
    env_file:
      - .env
    restart: unless-stopped
    expose:
      - '3009'

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: wpg-bus-tunnel
    restart: unless-stopped
    command: tunnel run
    volumes:
      - /home/fr3sh/.cloudflared:/home/nonroot/.cloudflared
    depends_on:
      - app
